let date = new Date(2023, 0, 2, 4, 30, 30);
console.log(date);
console.log(date.getFullYear());
console.log(date.getDate());
console.log(date.getDay());
console.log(date.getMonth());
console.log(date.getHours());
console.log(date.getMinutes());
console.log(date.getSeconds());
console.log(date.getMilliseconds());